version: '3.8'

services:
  web:
    image: my-flask-app:multistage
    # sampleregistry333.azurecr.io/hello-flask-mysql
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw